[package]
name = "rust-commitizen"
version = "0.1.0"
authors = ["Mars Peng <mars.90226@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "^0.11.2"
dialoguer = "^0.6.2"
rustyline = "^6.1.2"
